@echo off
echo Starting BlinderFit application...
cd "c:\Users\SUYASH KUMAR SINGH\OneDrive\Desktop\Blinderfit_"
echo Installing dependencies...
call npm install
echo Starting development server...
call npm run dev
echo Done!
