// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqwrxivhuugfntuqlkdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxd3J4aXZodXVnZm50dXFsa2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDA2NzksImV4cCI6MjA1OTc3NjY3OX0.ixrPXKNNPjxUnC7lOZlFH6GwMHgQa4IlexAU5jAejuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);